#ifndef __MAGIK_INFERENCEKIT_VENUS_INCLUDE_INFERENCE_KIT_VERSION_H__
#define __MAGIK_INFERENCEKIT_VENUS_INCLUDE_INFERENCE_KIT_VERSION_H__

/*toolchain*/
#define GCC_VERSION 7.2.0
#define GLIBC_VERSION 2.29
#define RELEASE_VERSION 5.1.5
/*source*/
#define BUILD_TIME 240308-01.09.02
#define PLATFORM mips
#define VENUS_GIT_HASH 8df640f
#define VENUS_VERSION_MAJOR 1
#define VENUS_VERSION_MINOR 2
#define VENUS_VERSION_PATCH 1
#define VENUS_VERSION_BUILD 0
#define VENUS_VERSION_AIE NNA1
#define VENUS_VERSION_SYS STANDARD
#define VENUS_VERSION_LIB STANDARD
#define VENUS_VERSION_TAG ALPHA
/*summary*/
#define VENUS_INFER_KIT_INFO 1.2.1.0.ALPHA
#define VENUS_BUILD_INFO 240308-01.09.02(7.2.0-r5.1.5-libc2.29-mips-lib@STANDARD-sys@STANDARD-aie@NNA1)
#endif//__MAGIK_INFERENCEKIT_VENUS_INCLUDE_INFERENCE_KIT_VERSION_H__
