#ifndef __MAGIK_INFERENCEKIT_VENUS_INCLUDE_COMMON_COMMON_ALG_H__
#define __MAGIK_INFERENCEKIT_VENUS_INCLUDE_COMMON_COMMON_ALG_H__

#ifndef ALGORITHM_ID
#define ALGORITHM_START(ALGORITHM_ID)
#define ALGORITHM_END(ALGORITHM_ID)
#else
#define ALGORITHM_START(ALGORITHM_ID) namespace ALGORITHM_ID {
#define ALGORITHM_END(ALGORITHM_ID) }
#endif

#define ALG_PACK_START ALGORITHM_START(ALGORITHM_ID)
#define ALG_PACK_END ALGORITHM_END(ALGORITHM_ID)
#endif /* __MAGIK_INFERENCEKIT_VENUS_INCLUDE_COMMON_COMMON_ALG_H__ */
