/*
 * sample-Encoder-jpeg.c
 *
 * Copyright (C) 2014 Ingenic Semiconductor Co.,Ltd
 *
 * The specific description of all APIs called in this file can be viewed in the header file in the proj/sdk-lv3/include/api/cn/imp/ directory
 * Step.1 System init system initialize
 *		@code
 *			memset(&sensor_info, 0, sizeof(sensor_info));
 *			if(SENSOR_NUM == IMPISP_TOTAL_ONE){
 *				memcpy(&sensor_info[0], &Def_Sensor_Info[0], sizeof(IMPSensorInfo));
 *			} else if(SENSOR_NUM == IMPISP_TOTAL_TWO){
 *				memcpy(&sensor_info[0], &Def_Sensor_Info[0], sizeof(IMPSensorInfo) * 2);
 *			}else if(SENSOR_NUM ==IMPISP_TOTAL_THR){
 *				memcpy(&sensor_info[0], &Def_Sensor_Info[0], sizeof(IMPSensorInfo) * 3)
 *			} //According to the number of sensors, copie the contents of the corresponding size Def_Sensor_Info to the sensor_info
 *
 *			ret = IMP_ISP_Open() //Open the ISP module
 *			ret = IMP_ISP_SetCameraInputMode(&mode) //If there are multiple sensors (maximum support of three cameras), set the mode to multiple cameras (please ignore if you're using single camera)
 *			ret = IMP_ISP_AddSensor(IMPVI_MAIN, &sensor_info[*]) //Add sensor,  before this operation the sensor driver has been added to the kernel (IMPVI_MAIN is main camera, IMPVI_SEC is second camera, IMPVI_THR is third camera)
 *			ret = IMP_ISP_EnableSensor(IMPVI_MAIN, &sensor_info[*])	//Enabel sensor, now sensor starts outputting image (IMPVI_MAIN is main camera, IMPVI_SE0C is second camera, IMPVI_THR is third camera)
 *			ret = IMP_System_Init() //System initialization
 *			ret = IMP_ISP_EnableTuning() //Enable ISP tuning before calling the ISP debugging interface
 *		@endcode
 * Step.2 FrameSource init Framesource initialization
 *		@code
 *			ret = IMP_FrameSource_CreateChn(chn[i].index, &chn[i].fs_chn_attr) //Create channel
 *			ret = IMP_FrameSource_SetChnAttr(chn[i].index, &chn[i].fs_chn_attr) //Set channel-related properties, including: image width, image height, image format, output frame rate of the channel, number of cache buf, cropping and scaling properties
 *		@endcode
 * Step.3 Encoder init Encoding initialization
 *		@code
 *			ret = IMP_Encoder_CreateGroup(chn[i].index) //Create a coding group
 *			ret = IMP_Encoder_SetDefaultParam(&channel_attr, IMP_ENC_PROFILE_JPEG, IMP_ENC_RC_MODE_FIXQP, imp_chn_attr_tmp->picWidth, imp_chn_attr_tmp->picHeight, 
 *											imp_chn_attr_tmp->outFrmRateNum, imp_chn_attr_tmp->outFrmRateDen, 0, 0, 25, 0) //Set the encoding chnnel default property
 *			ret = IMP_Encoder_CreateChn(4 + chn[i].index, &channel_attr) //Create coded chnnel
 *			ret = IMP_Encoder_RegisterChn(i, 4 + chn[i].index) //Register the code Channel to the Group
 *		@endcode
 * Step.4 Bind Bind a framesource and encode chnnel
 *		@code
 *			ret = IMP_System_Bind(&chn[i].framesource_chn, &chn[i].imp_encoder)	//Bind framesource and encoded chnnel, the data generated by the framesource can be automatically transmitted to the encoded chnnel after the binding is successful
 *		@endcode
 * Step.5 Stream On Enable Framesource chnnel, start outputting image
 *		@code
 *			ret = IMP_FrameSource_EnableChn(chn[i].index) //Enable chnnel, chnnel starts outputting image
 *		@endcode
 * Step.6 Get Snap  Get JPEG Encoding picture
 *		@code
 *			ret = IMP_Encoder_StartRecvPic(4 + chn[i].index) //Encoding chnnel start receiving image
 *			ret = IMP_Encoder_PollingStream(4 + chn[i].index, 1000) //Polling the code stream in the encoded chnnel
 *			ret = IMP_Encoder_GetStream(4 + chn[i].index, &stream, 1) //Gets the encoding bitstream
 *			ret = save_stream(snap_fd, &stream) //Save the result to an open file descriptor
 *			ret = IMP_Encoder_ReleaseStream(4 + chn[i].index, &stream) //Release the encoding bitstream, Used in pairs with IMP_Encoder_GetStream
 *			ret = IMP_Encoder_StopRecvPic(4 + chn[i].index) //Encode chnnel stops receiving images
 *		@endcode
 * Step.7 Stream Off Disable Framesource chnnel, stop outputting image
 *		@code
 *			ret = IMP_FrameSource_DisableChn(chn[i].index) //Disable channel, channel stop outputting image
 *		@endcode
 * Step.8 UnBind Unbind Framesource and code chnnel
 *		@code
 *			ret = IMP_System_UnBind(&chn[i].framesource_chn, &chn[i].imp_encoder) //Unbind the framesource and encode chnnel
 *		@endcode
 * Step.9 Encoder exit Encode deinitialization
 *		@code
 *			ret = IMP_Encoder_Query(chnNum, &chn_stat) //Query the encoding chnnel status
 *			ret = IMP_Encoder_UnRegisterChn(chnNum) //If already registered, unregister the code channel to Group
 *			ret = IMP_Encoder_DestroyChn(chnNum) //Destroy the code channel
 *		@endcode
 * Step.10 FrameSource exit Framesource deinitialization
 *		@code
 *			ret = IMP_FrameSource_DestroyChn(chn[i].index) //Destroy the channel
 *		@endcode
 * Step.11 System exit System deinitialization
 *		@code
 *			ret = IMP_ISP_DisableTuning() //Disable ISP tuning
 *			ret = IMP_System_Exit() //System deinitialization
 *			ret = IMP_ISP_DisableSensor(IMPVI_MAIN, &sensor_info[*]) //Disable sensor, sensor stop outputting image (IMPVI_MAIN is main camera, IMPVI_SEC is second camera, IMPVI_THR is third camera)
 *			ret = IMP_ISP_DelSensor(IMPVI_MAIN, &sensor_info[*]) //Delete sensor (IMPVI_MAIN is main camera, IMPVI_SEC is second camera, IMPVI_THR is third camera)
 *			ret = IMP_ISP_Close() //Disable ISP modules
 *		@endcode
 * */

#include <stdio.h>

#include <imp/imp_log.h>
#include <imp/imp_common.h>
#include <imp/imp_system.h>
#include <imp/imp_framesource.h>
#include <imp/imp_encoder.h>

#include "sample-common.h"

#define TAG "Sample-Encoder-jpeg"

extern struct chn_conf chn[];

int main(int argc, char *argv[])
{
	int i, ret;

	/* Step.1 System init */
	ret = sample_system_init();
	if (ret < 0) {
		IMP_LOG_ERR(TAG, "IMP_System_Init() failed\n");
		return -1;
	}

	/* Step.2 FrameSource init */
	ret = sample_framesource_init();
	if (ret < 0) {
		IMP_LOG_ERR(TAG, "FrameSource init failed\n");
		return -1;
	}

	/* Step.3 Encoder init */
	for (i = 0; i < FS_CHN_NUM; i++) {
		if (chn[i].enable) {
			ret = IMP_Encoder_CreateGroup(chn[i].index);
			if (ret < 0) {
				IMP_LOG_ERR(TAG, "IMP_Encoder_CreateGroup(%d) error !\n", i);
				return -1;
			}
		}
	}

	ret = sample_jpeg_init();
	if (ret < 0) {
		IMP_LOG_ERR(TAG, "Encoder init failed\n");
		return -1;
	}

	/* Step.4 Bind */
	for (i = 0; i < FS_CHN_NUM; i++) {
		if (chn[i].enable) {
			ret = IMP_System_Bind(&chn[i].framesource_chn, &chn[i].imp_encoder);
			if (ret < 0) {
				IMP_LOG_ERR(TAG, "Bind FrameSource channel%d and Encoder failed\n",i);
				return -1;
			}
		}
	}

	/* Step.5 Stream On */
	ret = sample_framesource_streamon();
	if (ret < 0) {
		IMP_LOG_ERR(TAG, "ImpStreamOn failed\n");
		return -1;
	}

	/* drop several pictures of invalid data */
	sleep(SLEEP_TIME);

	/* Step.6 Get Snap */
	ret = sample_get_jpeg_snap();
	if (ret < 0) {
		IMP_LOG_ERR(TAG, "Get H264 stream failed\n");
		return -1;
	}

	/* Exit sequence as follow... */
	/* Step.7 Stream Off */
	ret = sample_framesource_streamoff();
	if (ret < 0) {
		IMP_LOG_ERR(TAG, "FrameSource StreamOff failed\n");
		return -1;
	}

	/* Step.8 UnBind */
	for (i = 0; i < FS_CHN_NUM; i++) {
		if (chn[i].enable) {
			ret = IMP_System_UnBind(&chn[i].framesource_chn, &chn[i].imp_encoder);
			if (ret < 0) {
				IMP_LOG_ERR(TAG, "UnBind FrameSource channel%d and Encoder failed\n",i);
				return -1;
			}
		}
	}

	/* Step.9 Encoder exit */
	ret = sample_jpeg_exit();
	if (ret < 0) {
		IMP_LOG_ERR(TAG, "Encoder jpeg exit failed\n");
		return -1;
	}

	/* Step.10 FrameSource exit */
	ret = sample_framesource_exit();
	if (ret < 0) {
		IMP_LOG_ERR(TAG, "FrameSource exit failed\n");
		return -1;
	}

	/* Step.11 System exit */
	ret = sample_system_exit();
	if (ret < 0) {
		IMP_LOG_ERR(TAG, "sample_system_exit() failed\n");
		return -1;
	}

	return 0;
}
