#ifndef __VENUS_INFERENCE_KIT_VERSION_H__
#define __VENUS_INFERENCE_KIT_VERSION_H__

/*toolchain*/
#define GCC_VERSION 7.2.0
#define GLIBC_VERSION 2.29
#define RELEASE_VERSION 5.1.5
/*source*/
#define BUILD_TIME 230928-02.37.06
#define PLATFORM mips
#define CHIPNAME T40
#define VENUS_GIT_HASH ab20eb7
#define VENUS_VERSION_MAJOR 1
#define VENUS_VERSION_MINOR 1
#define VENUS_VERSION_PATCH 2
#define VENUS_VERSION_BUILD 1
#define VENUS_VERSION_AIE NNA1
#define VENUS_VERSION_TAG ALPHA
/*summary*/
#define VENUS_INFER_KIT_INFO 1.1.2.1.ALPHA
#define VENUS_BUILD_INFO 230928-02.37.06(7.2.0-r5.1.5-libc2.29-mips-T40@NNA1)
#endif//__VENUS_INFERENCE_KIT_VERSION_H__
